openapi: 3.0.1
info:
  title: DocGPT Plugin API
  description: |
    This API allows users to upload documents (PDFs or plain text), provide a URL or
    raw text, and either generate a concise summary or answer questions about the
    content. It is intended to be used as a ChatGPT plugin to make reading and
    analysing long documents fast and easy. Summaries are composed of the most
    informative sentences in the document, while the question answering endpoint
    returns the sentences that best match the user’s query.
  version: "1.0.0"

servers:
  - url: https://docgpt-plugin.onrender.com

paths:
  /summarize:
    post:
      operationId: summarize
      summary: Summarize a document from a URL, uploaded file, or raw text
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                url:
                  type: string
                  nullable: true
                  description: Public URL to fetch and summarize
                text:
                  type: string
                  nullable: true
                  description: Raw text to summarize
                file:
                  type: string
                  format: binary
                  nullable: true
                  description: PDF or text file to summarize
                sentences:
                  type: integer
                  default: 5
                  description: Number of sentences in the summary
      responses:
        "200":
          description: Summary result
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
        "400":
          description: Bad request
        "500":
          description: Server error

  /answer:
    post:
      operationId: answer
      summary: Answer a question based on a document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The user’s question
                url:
                  type: string
                  nullable: true
                  description: Public URL to fetch and read
                text:
                  type: string
                  nullable: true
                  description: Raw text to search for answers
                file:
                  type: string
                  format: binary
                  nullable: true
                  description: PDF or text file to analyze
                top_sentences:
                  type: integer
                  default: 3
                  description: Number of sentences to return
      responses:
        "200":
          description: Answer result
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
        "400":
          description: Bad request
        "500":
          description: Server error
